version: '3.8'

volumes:
  mymoviescoreDB:

networks:
  sqlserverNET:
  mymoviescoreNet:

services:

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sqlserver
    ports:
      - "1433:1433"
    volumes:
      - mymoviescoreDB:/var/lib/sqlserver
    networks:
      - sqlserverNET
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: numsey#2021
      MSSQL_PID: EXPRESS
      
  mymoviescore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mymoviescore
    networks:
      - sqlserverNET
      - mymoviescoreNet   
    ports:
     - "5000:80"
    environment:
      - DBHOST=sqlserver
    depends_on:
      - sqlserver
